controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

cooolinho_security:
    resource: ../../vendor/cooolinho/symfony-security-bundle/src/Controller/
    type: annotation
