security:
    enable_authenticator_manager: true
    encoders:
        Cooolinho\Bundle\SecurityBundle\Entity\User:
            algorithm: auto
        App\Entity\Trainer:
            algorithm: auto

    providers:
        app_admin_provider:
            entity:
                class: Cooolinho\Bundle\SecurityBundle\Entity\User
                property: email
        app_trainer_provider:
            entity:
                class: App\Entity\Trainer
                property: email
        all_users:
            chain:
                providers: [ 'app_admin_provider', 'app_trainer_provider' ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_admin_area:
            lazy: true
            pattern: ^/admin
            provider: all_users
            user_checker: App\Security\Admin\UserChecker
            custom_authenticator:
                - App\Security\Admin\Authenticator
            logout:
                path: admin_logout
                target: home
        secured_trainer_area:
            lazy: true
            pattern: ^/trainer
            provider: all_users
            user_checker: App\Security\Trainer\UserChecker
            custom_authenticator:
                - App\Security\Trainer\Authenticator
            logout:
                path: trainer_logout
                target: home

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_ADMIN: ROLE_USER
        ROLE_TRAINER: ROLE_USER

    access_control:
        - { path: ^/trainer/login, roles: PUBLIC_ACCESS }
        - { path: ^/trainer/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/trainer, roles: ROLE_TRAINER }
