twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/admin': admin
        '%kernel.project_dir%/templates/trainer': trainer
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
