services:
    _defaults:
        autowire: true
        autoconfigure: true

    Cooolinho\Bundle\FileImporterBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Resources,Tests}'

    Cooolinho\Bundle\FileImporterBundle\Controller\:
        resource: '../../../src/Controller'
        tags: [ 'controller.service_arguments' ]
